// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// NOTA (SPR-003): este arquivo é lido pela CLI do Prisma (migrate/generate/studio),
// fora do bootstrap do Nest, portanto não há container de DI disponível e o
// ConfigService não pode ser injetado aqui. O uso de process.env é uma exceção
// intencional e documentada ao critério de aceite "nenhum process.env fora do
// módulo de configuração", restrita a este arquivo de configuração de build/CLI.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
