// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// NOTA (SPR-003): a partir do Prisma 7, a URL de conexão não é mais
// declarada no schema.prisma (repare que não há `url = env("DATABASE_URL")`
// no datasource abaixo) — ela é resolvida aqui, neste arquivo de config
// dedicado, lido diretamente pela CLI do Prisma (migrate/generate/studio).
// Esse comando roda como um processo isolado, fora do bootstrap do Nest,
// então não existe container de DI e o AppConfigService/ConfigService não
// podem ser injetados. Por isso process.env é usado diretamente aqui — uma
// exceção intencional e documentada ao critério de aceite "nenhum
// process.env fora do módulo de configuração", restrita a este arquivo de
// configuração de build/CLI.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
